version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
1443fea48df94037c27382ab9d269549467fc1ea  /home/maven/repository-staging/to-ibiblio/maven2/HTTPClient/HTTPClient/maven-metadata.xml
